webapp:
    build: .
    ports: ['3000:3000']
    volumes: ['.:/openfarm']
    links: ['mongo']
    environment:
        S3_BUCKET_NAME:
        S3_ACCESS_KEY:
        S3_SECRET_KEY:
        SERVER_S3_ACCESS_KEY:
        SERVER_S3_SECRET_KEY:
        ALERTS:
        MONGO_HOST: mongo_1

mongo:
    image: 'mongo:2.6'
